# Generated by Django 6.0.1 on 2026-01-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(default='معًا نصنع التعليم… شركاء في بناء المستقبل', max_length=200, verbose_name='اسم اللوحة')),
                ('cards_speed', models.PositiveIntegerField(default=40, help_text='كلما زاد الرقم أصبحت الحركة أبطأ', verbose_name='سرعة حركة البطاقات (بالثواني)')),
                ('background_color', models.CharField(default='#0FA968', max_length=7, verbose_name='لون الخلفية الرئيسي')),
                ('card_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='لون البطاقة')),
                ('card_text_color', models.CharField(default='#1B4F72', max_length=7, verbose_name='لون نص البطاقة')),
                ('neon_color', models.CharField(default='#2EC4B6', max_length=7, verbose_name='لون النيون حول البطاقة')),
                ('ministry_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار وزارة التعليم')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المدرسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات اللوحة',
                'verbose_name_plural': 'إعدادات اللوحة',
            },
        ),
    ]
