# Generated by Django 6.0.1 on 2026-01-25 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='اسم ولي الأمر')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالبة')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز التعديل والحذف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة للعرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'رسالة ولي أمر',
                'verbose_name_plural': 'رسائل أولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
    ]
