# Generated by Django 6.0.1 on 2026-01-25 16:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsettings',
            name='ministry_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار وزارة التعليم'),
        ),
        migrations.AlterField(
            model_name='boardsettings',
            name='school_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار المدرسة'),
        ),
    ]
